import type { FieldMeta } from "../../types";

export const fields: FieldMeta[] = [
  { key: "invoiceDate", label: "BIG01 Invoice Date", dataType: "Date (YYYYMMDD)", mandatory: true, scope: "header" },
  { key: "invoiceNumber", label: "BIG02 Invoice Number", dataType: "AlphaNumeric (1/18)", mandatory: true, scope: "header" },
  { key: "poDate", label: "BIG03 PO Date", dataType: "Date (YYYYMMDD)", mandatory: false, scope: "header" },
  { key: "poNumber", label: "BIG04 PO Number", dataType: "AlphaNumeric", mandatory: false, scope: "header" },
  { key: "creditDebitIndicator", label: "BIG07 Credit/Debit Indicator", dataType: "CR or DI", mandatory: false, scope: "header", notes: "Principal credit/debit indicator for US Foods" },
  { key: "shipTo.name", label: "N1(ST)02 Location/Name", dataType: "AlphaNumeric (1/60)", mandatory: true, scope: "header" },
  { key: "shipTo.vendorStoreId", label: "N1(ST)04 Customer Number", dataType: "AlphaNumeric (1/80)", mandatory: true, scope: "header" },
  { key: "shipTo.address1", label: "N301 Address 1", dataType: "AlphaNumeric (1/40)", mandatory: false, scope: "header" },
  { key: "shipTo.city", label: "N401 City", dataType: "AlphaNumeric (1/40)", mandatory: false, scope: "header" },
  { key: "shipTo.state", label: "N402 State", dataType: "Identifier (2/2)", mandatory: false, scope: "header" },
  { key: "shipTo.zip", label: "N403 Zip Code", dataType: "AlphaNumeric (5/5)", mandatory: false, scope: "header" },
  { key: "dueDate", label: "ITD06 Due Date", dataType: "Date (YYYYMMDD)", mandatory: false, scope: "header" },
  { key: "lineItems[].quantity", label: "IT102 Quantity", dataType: "Numeric (1/10)", mandatory: true, scope: "lineItem", notes: "Negative on credit lines; decimal allowed for LB UOM" },
  { key: "lineItems[].uom", label: "IT103 Unit of Measure", dataType: "CA, EA, LB", mandatory: true, scope: "lineItem" },
  { key: "lineItems[].unitPrice", label: "IT104 Unit Price", dataType: "Numeric (1/17)", mandatory: true, scope: "lineItem" },
  { key: "lineItems[].basisOfUnitPriceCode", label: "IT105 Basis of Unit Price", dataType: "PE, PP, UM", mandatory: false, scope: "lineItem" },
  { key: "lineItems[].upcPack", label: "IT107 Pack UPC", dataType: "AlphaNumeric (1/14)", mandatory: false, scope: "lineItem" },
  { key: "lineItems[].upcCase", label: "IT109 Case UPC", dataType: "AlphaNumeric (1/14)", mandatory: false, scope: "lineItem" },
  { key: "lineItems[].itemNumber", label: "IT111 Item Number", dataType: "AlphaNumeric (1/48)", mandatory: true, scope: "lineItem", notes: "VIN" },
  { key: "lineItems[].manufacturerPartNumber", label: "IT113 Manufacturer Part Number", dataType: "AlphaNumeric (1/48)", mandatory: false, scope: "lineItem" },
  { key: "lineItems[].substituteProductNumber", label: "IT115 Substitute Product Number", dataType: "AlphaNumeric (1/48)", mandatory: false, scope: "lineItem" },
  { key: "lineItems[].brandLabel", label: "IT123 Brand Label", dataType: "AlphaNumeric (1/48)", mandatory: false, scope: "lineItem" },
  { key: "lineItems[].description", label: "PID05 Description", dataType: "AlphaNumeric (1/80)", mandatory: true, scope: "lineItem" },
  { key: "lineItems[].lineTax.amount", label: "TXI02 Monetary Amount (line)", dataType: "Double", mandatory: false, scope: "charge", notes: "Mapped to SAC code H850" },
  { key: "lineItems[].charges[].code", label: "SAC02 SAC Code", dataType: "A170, B950, C040, C650, D240, F340, F800, G970, H625, H840, H850, C110, F810", mandatory: false, scope: "charge" },
  { key: "lineItems[].charges[].amount", label: "SAC05 Total", dataType: "Numeric, implied decimal", mandatory: false, scope: "charge" },
  { key: "summaryTax.type", label: "TXI01 Tax Type (summary)", dataType: "LS (loadable) or TX (reference only)", mandatory: false, scope: "header" },
  { key: "summaryTax.amount", label: "TXI02 Monetary Amount (summary)", dataType: "Double", mandatory: false, scope: "header" },
  { key: "summaryTax.percent", label: "TXI03 Percent", dataType: "Double", mandatory: false, scope: "header" },
];
